import { Geist, Geist_Mono, Noto_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const notoSerif = Noto_Serif({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight:["300", "400"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${notoSerif.className} min-h-full flex flex-col `}>

        {children}
        
        </body>
    </html>
  );
}
